'use strict';

const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const ships={
  Cutlass:{maker:'Drake',variants:{Black:[46,'Medium freight'],Blue:[12,'Interdiction'],Red:[12,'Medical support'],Steel:[18,'Dropship']}},
  Constellation:{maker:'RSI',variants:{Andromeda:[96,'Gunship freight'],Aquila:[96,'Expedition freight'],Phoenix:[80,'Luxury transport'],Taurus:[174,'Heavy freight']}},
  Freelancer:{maker:'MISC',variants:{Base:[66,'Medium freight'],DUR:[36,'Expedition'],MAX:[120,'Heavy freight'],MIS:[36,'Missile gunship']}},
  'Zeus Mk II':{maker:'RSI',variants:{CL:[128,'Medium freight'],ES:[32,'Expedition'],MR:[16,'Security']}},
  Caterpillar:{maker:'Drake',variants:{Base:[576,'Heavy modular freight']}},
  'C2 Hercules':{maker:'Crusader',variants:{C2:[696,'Ultra-heavy freight']}},
  RAFT:{maker:'ARGO',variants:{Base:[96,'Container freight']}},
  Hull:{maker:'MISC',variants:{A:[64,'Light external freight'],B:[384,'External freight'],C:[4608,'Inter-system freight']}}
};
const commodities=[
  ['Agricium','Legal'],['Agricultural Supplies','Legal'],['Altruciatoxin','Illegal'],['Astatine','Legal'],['Beryl','Legal'],['Construction Materials','Legal'],['Copper','Legal'],['Corundum','Legal'],['Distilled Spirits','Legal'],["E'tam",'Controlled'],['Fluorine','Legal'],['Gold','Legal'],['Hydrogen','Legal'],['Laranite','Legal'],['Medical Supplies','Legal'],['Processed Food','Legal'],['Quantanium','Legal'],['Recycled Material Composite','Legal'],['Scrap','Legal'],['Stims','Controlled'],['Titanium','Legal'],['Tungsten','Legal'],['Waste','Legal'],['WiDoW','Illegal']
].map(([name,legality])=>({name,legality})).sort((a,b)=>a.name.localeCompare(b.name));
const locations=[
 ['Area18',['A18'],'ArcCorp','Landing Zone',745,205],['Baijini Point',['Baijini'],'ArcCorp','Orbital Station',705,240],['ArcCorp Mining Area 045',['AMA 045'],'Wala','Outpost',820,276],['ArcCorp Mining Area 056',['AMA 056'],'Wala','Outpost',790,300],['Everus Harbor',['Everus'],'Hurston','Orbital Station',350,258],['Lorville',['Teasa'],'Hurston','Landing Zone',318,286],['HDMS-Bezdek',['Bezdek'],'Arial','Outpost',255,232],['HDMS-Lathan',['Lathan'],'Arial','Outpost',275,212],['HDMS-Edmond',['Edmond'],'Hurston','Outpost',287,330],['HUR-L1 Green Glade Station',['HUR-L1','Green Glade'],'Hurston','Lagrange Station',250,360],['Orison',['August Dunlow'],'Crusader','Landing Zone',540,525],['Seraphim Station',['Seraphim'],'Crusader','Orbital Station',510,486],["Brio’s Breaker Yard",['Brios',"Brio's"],'Daymar','Scrapyard',454,566],['Shubin Mining Facility SCD-1',['SCD-1'],'Daymar','Outpost',481,587],['New Babbage',['NB','NBIS'],'microTech','Landing Zone',712,474],['Port Tressler',['Tressler'],'microTech','Orbital Station',682,444],['Shubin Mining Facility SM0-18',['SM0-18'],'microTech','Outpost',760,520],['Rayari Deltana Research Outpost',['Rayari Deltana','Deltana'],'microTech','Research Outpost',790,490],['MIC-L1 Shallow Frontier Station',['MIC-L1','Shallow Frontier'],'microTech','Lagrange Station',850,412],['Grim HEX',['GH','Grimhex'],'Yela','Asteroid Station',582,558],['Pyro Gateway',['Pyro Jump Point'],'Stanton','Jump Point',90,110],['Terra Gateway',['Terra Jump Point'],'Stanton','Jump Point',900,105],['Magnus Gateway',['Magnus Jump Point'],'Stanton','Jump Point',910,585]
].map(([name,aliases,parent,type,x,y])=>({name,aliases,parent,type,system:'Stanton',x,y}));
const maps={
 system:[
  ['stanton','Stanton','Star','G-type main sequence',500,340,18,'star-node','The central star of the Stanton system.'],
  ['hurston','Hurston','Planet','Hurston Dynamics',318,286,13,'planet-node','Industrial world with Lorville and four moons.','Hurston'],
  ['crusader','Crusader','Gas Giant','Crusader Industries',540,525,18,'planet-node','Gas giant with Orison and three moons.','Crusader'],
  ['arccorp','ArcCorp','Planet','ArcCorp jurisdiction',745,205,12,'planet-node','Planet-wide city and industrial hub.','ArcCorp'],
  ['microtech','microTech','Planet','microTech jurisdiction',712,474,14,'planet-node','Cold high-tech world with New Babbage.','microTech'],
  ['pyro','Pyro Gateway','Jump Point','To Pyro system',90,110,11,'gateway-node','Gateway connecting Stanton to Pyro.'],
  ['terra','Terra Gateway','Jump Point','To Terra system',900,105,11,'gateway-node','Gateway connecting Stanton to Terra.'],
  ['magnus','Magnus Gateway','Jump Point','To Magnus system',910,585,11,'gateway-node','Gateway connecting Stanton to Magnus.']
 ],
 Hurston:[['h0','Hurston','Planet','Primary',500,340,30,'planet-node','Hurston Dynamics industrial headquarters.'],['lor','Lorville','Landing Zone','Hurston',540,300,9,'location-node','Primary industrial city.'],['eve','Everus Harbor','Orbital Station','Hurston orbit',430,250,8,'station-node','Orbital station above Lorville.'],['ari','Arial','Moon','Hurston I',275,210,12,'planet-node','Hot mining moon.'],['abe','Aberdeen','Moon','Hurston II',730,220,13,'planet-node','Hazardous moon.'],['mag','Magda','Moon','Hurston III',780,475,11,'planet-node','Rocky mining moon.'],['ita','Ita','Moon','Hurston IV',260,500,11,'planet-node','Mineral-rich moon.'],['bez','HDMS-Bezdek','Outpost','Arial',215,175,6,'location-node','Surface logistics outpost.'],['lat','HDMS-Lathan','Outpost','Arial',318,166,6,'location-node','Surface logistics outpost.']],
 Crusader:[['c0','Crusader','Gas Giant','Primary',500,340,42,'planet-node','Crusader Industries headquarters.'],['ori','Orison','Landing Zone','Crusader atmosphere',550,382,9,'location-node','Floating city and landing zone.'],['ser','Seraphim Station','Orbital Station','Crusader orbit',410,245,8,'station-node','Primary orbital station.'],['cel','Cellin','Moon','Crusader I',265,220,11,'planet-node','Volcanic moon.'],['day','Daymar','Moon','Crusader II',730,225,13,'planet-node','Desert moon.'],['yel','Yela','Moon','Crusader III',745,490,12,'planet-node','Ice moon with asteroid belt.'],['ghe','Grim HEX','Asteroid Station','Yela belt',805,545,7,'station-node','Independent asteroid station.'],['bri','Brio’s Breaker Yard','Scrapyard','Daymar',792,270,6,'location-node','Surface scrapyard.']],
 ArcCorp:[['a0','ArcCorp','Planet','Primary',500,340,31,'planet-node','Planet-wide urban world.'],['a18','Area18','Landing Zone','ArcCorp',548,295,9,'location-node','Primary commercial district.'],['bai','Baijini Point','Orbital Station','ArcCorp orbit',410,245,8,'station-node','Orbital station above Area18.'],['lyr','Lyria','Moon','ArcCorp I',270,245,12,'planet-node','Cold mining moon.'],['wal','Wala','Moon','ArcCorp II',735,440,12,'planet-node','Rocky industrial moon.'],['045','ArcCorp Mining Area 045','Outpost','Wala',802,405,6,'location-node','Mining outpost.'],['056','ArcCorp Mining Area 056','Outpost','Wala',785,492,6,'location-node','Mining outpost.']],
 microTech:[['m0','microTech','Planet','Primary',500,340,34,'planet-node','Cold high-tech corporate world.'],['nb','New Babbage','Landing Zone','microTech',548,300,9,'location-node','Primary technology campus.'],['pt','Port Tressler','Orbital Station','microTech orbit',410,238,8,'station-node','Orbital station above New Babbage.'],['cal','Calliope','Moon','microTech I',255,215,11,'planet-node','Frozen moon.'],['cli','Clio','Moon','microTech II',735,230,12,'planet-node','Ice moon with research sites.'],['eut','Euterpe','Moon','microTech III',720,490,12,'planet-node','Frozen industrial moon.'],['del','Rayari Deltana Research Outpost','Research Outpost','microTech',605,440,6,'location-node','Research and freight destination.'],['sm','Shubin Mining Facility SM0-18','Outpost','microTech',405,455,6,'location-node','Mining facility.']]
};
Object.keys(maps).forEach(k=>maps[k]=maps[k].map(([id,name,type,meta,x,y,size,cls,description,focus])=>({id,name,type,meta,x,y,size,cls,description,focus})));
const defaults={family:'Cutlass',variant:'Black',start:'Everus Harbor',contracts:[
 {commodity:'Titanium',scu:24,pickup:'HDMS-Bezdek',delivery:'Area18',reward:92500,note:''},
 {commodity:'Medical Supplies',scu:18,pickup:'Everus Harbor',delivery:'Port Tressler',reward:70000,note:'Keep accessible near ramp'}
]};
const state={...defaults,contracts:defaults.contracts.map(x=>({...x})),calculated:false,active:false,route:[],focus:'system',selected:null,transform:{x:0,y:0,scale:1}};
const el={family:$('#shipFamily'),variant:$('#shipVariant'),start:$('#startLocation'),contracts:$('#cargoContracts'),template:$('#cargoContractTemplate'),nodes:$('#mapNodes'),overlay:$('#routeOverlay'),viewport:$('#mapViewport'),stage:$('#mapStage'),tooltip:$('#mapTooltip'),timeline:$('#routeTimeline'),status:$('#routeStatus'),calc:$('#calculateRoute'),startRoute:$('#startRoute'),toast:$('#toastRegion')};
const esc=v=>String(v??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const norm=v=>String(v||'').toLowerCase().replace(/[’']/g,'').replace(/[^a-z0-9]/g,'');
const ship=()=>{const f=ships[state.family],d=f.variants[state.variant]||Object.values(f.variants)[0];return {maker:f.maker,scu:d[0],role:d[1]}};
const shipName=()=>`${ship().maker} ${state.family}${state.variant==='Base'?'':` ${state.variant}`}`;
function save(){try{localStorage.setItem('sc-companion-planner-v1',JSON.stringify({family:state.family,variant:state.variant,start:el.start.value,contracts:state.contracts}))}catch{}}
function load(){try{const s=JSON.parse(localStorage.getItem('sc-companion-planner-v1'));if(!s)return;if(ships[s.family]){state.family=s.family;state.variant=s.variant}if(typeof s.start==='string')state.start=s.start;if(Array.isArray(s.contracts)&&s.contracts.length)state.contracts=s.contracts}catch{}}
function toast(msg){const n=document.createElement('div');n.className='toast';n.textContent=msg;el.toast.append(n);setTimeout(()=>{n.style.opacity=0;setTimeout(()=>n.remove(),220)},2700)}
function dirty(render=true){state.calculated=false;state.active=false;el.status.className='draft-pill';el.status.innerHTML='<i></i>Draft';el.startRoute.disabled=true;el.calc.querySelector('span').textContent='Calculate route';next('Review cargo and calculate','The planner will deduce pickup and delivery sequencing from your contracts.');if(render){metrics();renderMap()}save()}
function next(title,copy){$('#nextStepCard strong').textContent=title;$('#nextStepCard p').textContent=copy}
function initShips(){el.family.innerHTML=Object.keys(ships).map(x=>`<option>${esc(x)}</option>`).join('');el.family.value=state.family;variants();el.family.onchange=()=>{state.family=el.family.value;state.variant=Object.keys(ships[state.family].variants)[0];variants();updateShip();dirty()};el.variant.onchange=()=>{state.variant=el.variant.value;updateShip();dirty()}}
function variants(){el.variant.innerHTML=Object.keys(ships[state.family].variants).map(x=>`<option>${esc(x)}</option>`).join('');el.variant.value=state.variant}
function updateShip(){const s=ship();$('#shipName').textContent=shipName();$('#shipMeta').textContent=`${s.scu.toLocaleString()} SCU · ${s.role}`;metrics()}
function renderContracts(){el.contracts.innerHTML='';state.contracts.forEach((c,i)=>{const f=el.template.content.cloneNode(true),card=$('.cargo-contract',f);card.dataset.index=i;$('.contract-label',f).textContent=`Contract ${String(i+1).padStart(2,'0')}`;$('.contract-path',f).textContent=`${c.pickup||'Pickup'} → ${c.delivery||'Delivery'}`;[['.commodity-input','commodity'],['.scu-input','scu'],['.pickup-input','pickup'],['.delivery-input','delivery'],['.reward-input','reward'],['.note-input','note']].forEach(([sel,key])=>{const inp=$(sel,f);inp.value=c[key]??'';inp.oninput=()=>{state.contracts[i][key]=['scu','reward'].includes(key)?Math.max(0,Number(inp.value)||0):inp.value;$('.contract-path',card).textContent=`${state.contracts[i].pickup||'Pickup'} → ${state.contracts[i].delivery||'Delivery'}`;metrics();dirty(false)};inp.onchange=()=>{save();renderMap()}});$('.duplicate-contract',f).onclick=()=>{state.contracts.splice(i+1,0,{...c});renderContracts();dirty()};$('.delete-contract',f).onclick=()=>{state.contracts.splice(i,1);renderContracts();dirty();toast('Cargo contract removed.')};drag(card);el.contracts.append(f)});autocomplete(el.contracts);metrics()}
function drag(card){card.ondragstart=e=>{card.classList.add('is-dragging');e.dataTransfer.setData('text/plain',card.dataset.index)};card.ondragend=()=>card.classList.remove('is-dragging');card.ondragover=e=>e.preventDefault();card.ondrop=e=>{e.preventDefault();const from=Number(e.dataTransfer.getData('text/plain')),to=Number(card.dataset.index);if(from===to)return;const [m]=state.contracts.splice(from,1);state.contracts.splice(to,0,m);renderContracts();dirty()}}
function autocomplete(root=document){$$('.autocomplete-field',root).forEach(w=>{if(w.dataset.ready)return;w.dataset.ready=1;const input=$('input',w),menu=$('.autocomplete-menu',w),kind=w.dataset.autocomplete;let focused=-1,items=[];const close=()=>{menu.classList.remove('is-open');input.setAttribute('aria-expanded','false');focused=-1};const select=item=>{input.value=item.name;if(kind==='ship'){state.family=item.family;state.variant=item.variant;el.family.value=state.family;variants();el.variant.value=state.variant;updateShip()}else{input.dispatchEvent(new Event('input',{bubbles:true}));if(input===el.start)state.start=item.name}close();dirty();renderMap()};const draw=()=>{const q=input.value.trim().toLowerCase();if(kind==='ship')items=Object.entries(ships).flatMap(([family,f])=>Object.entries(f.variants).map(([variant,d])=>({name:`${family}${variant==='Base'?'':` ${variant}`}`,meta:`${f.maker} · ${d[0]} SCU`,family,variant}))).filter(x=>`${x.name} ${x.meta}`.toLowerCase().includes(q)).slice(0,8);else if(kind==='commodity')items=commodities.filter(x=>x.name.toLowerCase().includes(q)).slice(0,8).map(x=>({name:x.name,meta:x.legality,tag:x.legality}));else items=locations.filter(x=>[x.name,x.parent,x.type,...x.aliases].some(v=>v.toLowerCase().includes(q))).sort((a,b)=>a.name.localeCompare(b.name)).slice(0,9).map(x=>({name:x.name,meta:`Stanton · ${x.parent}`,tag:x.type}));focused=-1;menu.innerHTML=items.length?items.map((x,i)=>`<button type="button" class="autocomplete-option" data-i="${i}"><span><strong>${esc(x.name)}</strong><small>${esc(x.meta)}</small></span>${x.tag?`<em>${esc(x.tag)}</em>`:''}</button>`).join(''):`<div class="autocomplete-empty">No verified match. Keep “${esc(input.value)}” as a custom value.</div>`;$$('.autocomplete-option',menu).forEach((b,i)=>b.onmousedown=e=>{e.preventDefault();select(items[i])});menu.classList.add('is-open');input.setAttribute('aria-expanded','true')};input.onfocus=draw;input.addEventListener('input',draw);input.onblur=()=>setTimeout(close,90);input.onkeydown=e=>{const opts=$$('.autocomplete-option',menu);if(e.key==='ArrowDown'&&opts.length){e.preventDefault();focused=(focused+1)%opts.length}else if(e.key==='ArrowUp'&&opts.length){e.preventDefault();focused=(focused-1+opts.length)%opts.length}else if(e.key==='Enter'){if(focused>=0){e.preventDefault();opts[focused].dispatchEvent(new MouseEvent('mousedown'))}else close()}else if(e.key==='Escape')close();opts.forEach((o,i)=>o.classList.toggle('is-focused',i===focused))}})}
function metrics(){const total=state.contracts.reduce((s,c)=>s+(Number(c.scu)||0),0),cap=ship().scu,reward=state.contracts.reduce((s,c)=>s+(Number(c.reward)||0),0),stops=new Set([el.start.value,...state.contracts.flatMap(c=>[c.pickup,c.delivery])].filter(Boolean)),pct=cap?Math.round(total/cap*100):0;$('#plannedScu').textContent=total.toLocaleString();$('#capacityScu').textContent=cap.toLocaleString();$('#capacityBar').style.width=`${Math.min(pct,100)}%`;$('#capacityText').textContent=`${pct}% capacity`;$('#capacityFree').textContent=total<=cap?`${(cap-total).toLocaleString()} SCU free`:`${(total-cap).toLocaleString()} SCU over`;$('.capacity-card').classList.toggle('is-over',total>cap);$('#rewardMetric').textContent=reward?reward.toLocaleString():'—';$('#stopsMetric').textContent=Math.max(stops.size,1);$('#cargoSectionMeta').textContent=`${state.contracts.length} contract${state.contracts.length===1?'':'s'} · ${total.toLocaleString()} SCU`;if(!state.calculated)timeline(route().slice(0,5),true)}
function route(){const start=el.start.value.trim()||'Custom starting location',out=[{name:start,type:'start',cargo:'Departure point'}],p=new Map(),d=new Map();state.contracts.forEach(c=>{if(c.pickup&&norm(c.pickup)!==norm(start)){if(!p.has(c.pickup))p.set(c.pickup,[]);p.get(c.pickup).push(c)}if(c.delivery){if(!d.has(c.delivery))d.set(c.delivery,[]);d.get(c.delivery).push(c)}});for(const [name,cs] of p)out.push({name,type:'pickup',cargo:`Load ${cs.reduce((s,c)=>s+Number(c.scu||0),0)} SCU · ${cs.map(c=>c.commodity||'Custom cargo').join(', ')}`});for(const [name,cs] of d)out.push({name,type:'delivery',cargo:`Deliver ${cs.reduce((s,c)=>s+Number(c.scu||0),0)} SCU · ${cs.map(c=>c.commodity||'Custom cargo').join(', ')}`});return out.filter((x,i,a)=>a.findIndex(y=>norm(y.name)===norm(x.name))===i)}
function timeline(r,draft=false){el.timeline.innerHTML=r.map((s,i)=>`<li><span class="timeline-dot ${s.type}">${String(i+1).padStart(2,'0')}</span><div class="timeline-copy"><strong>${esc(s.name)}</strong><span>${esc(s.cargo)}</span></div><span class="timeline-distance">${i===0?'START':draft?'—':`${(2.4+i*1.7).toFixed(1)} Gm`}</span></li>`).join('')}
function calculate(){if(!state.contracts.length)return toast('Add at least one cargo contract.');if(state.contracts.some(c=>!c.commodity.trim()||!c.pickup.trim()||!c.delivery.trim()||Number(c.scu)<=0))return toast('Complete every cargo contract.');const total=state.contracts.reduce((s,c)=>s+Number(c.scu||0),0);if(total>ship().scu)return toast(`Cargo exceeds ${shipName()} capacity by ${total-ship().scu} SCU.`);el.calc.disabled=true;el.calc.classList.add('is-loading');el.calc.querySelector('span').textContent='Optimizing…';setTimeout(()=>{state.route=route();state.calculated=true;const known=state.route.map(s=>locations.find(l=>norm(l.name)===norm(s.name))).filter(Boolean);let dist=0;for(let i=1;i<known.length;i++)dist+=Math.hypot(known[i].x-known[i-1].x,known[i].y-known[i-1].y)/36;dist=Math.max(dist,state.route.length*2.7);$('#distanceMetric').textContent=`${dist.toFixed(1)} Gm`;$('#durationMetric').textContent=`${Math.round(12+state.route.length*4.5+total*.12)} min`;$('#stopsMetric').textContent=state.route.length;timeline(state.route);renderMap();el.status.className='draft-pill is-ready';el.status.innerHTML='<i></i>Ready';el.startRoute.disabled=false;el.calc.disabled=false;el.calc.classList.remove('is-loading');el.calc.querySelector('span').textContent='Recalculate';next(`Depart ${state.route[0].name}`,`${state.route.length-1} operational stops are ready for preview.`);$('[data-map-mode="route"]').click();save();toast('Route preview ready.')},620)}
function startRoute(){if(!state.calculated)return;state.active=true;el.status.className='draft-pill is-active';el.status.innerHTML='<i></i>Active';el.startRoute.innerHTML='<svg viewBox="0 0 24 24"><path d="M6 12h12M13 7l5 5-5 5"/></svg> Open active route';next(`Fly to ${state.route[1]?.name||state.route[0].name}`,state.route[1]?.cargo||'Route is active.');toast('Route started. Active tracking comes next.');save()}
function rclass(name){const hit=(state.calculated?state.route:route()).find(s=>norm(s.name)===norm(name)||parentOf(s.name)===name);return hit?`is-route-stop is-${hit.type}`:''}
function parentOf(name){return locations.find(l=>norm(l.name)===norm(name))?.parent||''}
function label(n){if(n.x>800)return[-n.size-12,-2,'end'];if(n.x<180)return[n.size+12,-2,'start'];if(n.y<180)return[0,n.size+24,'middle'];return[n.size+12,-2,'start']}
function renderMap(){const list=maps[state.focus]||maps.system;el.nodes.innerHTML=list.map(n=>{const [x,y,a]=label(n),sel=state.selected?.id===n.id?' is-selected':'';return `<g class="map-node ${n.cls} ${rclass(n.name)}${sel}" data-id="${n.id}" transform="translate(${n.x} ${n.y})">${n.cls==='star-node'?'<circle class="star-glow" r="62"/>':''}<circle class="node-hit" r="${Math.max(n.size+18,28)}"/><circle class="node-ring" r="${n.size+6}"/><circle class="node-core" r="${n.size}"/><text class="node-label" x="${x}" y="${y}" text-anchor="${a}">${esc(n.name)}</text><text class="node-meta" x="${x}" y="${y+13}" text-anchor="${a}">${esc(n.meta)}</text></g>`}).join('');$$('.map-node',el.nodes).forEach(g=>{const n=list.find(x=>x.id===g.dataset.id);g.onmouseenter=e=>tip(e,n);g.onmousemove=moveTip;g.onmouseleave=()=>el.tooltip.classList.remove('is-visible');g.onclick=e=>{e.stopPropagation();state.selected=n;renderMap();context(n);$('#focusSelected').disabled=!n.focus};g.ondblclick=e=>{e.stopPropagation();if(n.focus)focus(n.focus)}});overlay();breadcrumbs();$('#mapLevelLabel').textContent=state.focus==='system'?'System':'Planetary';$('#routeNodeCount').textContent=(state.calculated?state.route:route()).length;applyTransform()}
function coords(name){const loc=locations.find(l=>norm(l.name)===norm(name));if(state.focus==='system'){let parent=loc?.parent,j=['Hurston','Crusader','ArcCorp','microTech'].includes(parent)?parent:locations.find(l=>l.name===parent)?.parent;const n=maps.system.find(x=>norm(x.name)===norm(name)||x.name===j||x.name===parent);return n&&{x:n.x,y:n.y}}const n=(maps[state.focus]||[]).find(x=>norm(x.name)===norm(name)||norm(x.name)===norm(loc?.parent));return n&&{x:n.x,y:n.y}}
function overlay(){const pts=(state.calculated?state.route:route()).map(s=>coords(s.name)).filter(Boolean);if(pts.length<2){el.overlay.innerHTML='';return}const d=pts.map((p,i)=>`${i?'L':'M'} ${p.x} ${p.y}`).join(' ');el.overlay.innerHTML=`<path class="route-path-underlay" d="${d}"/><path class="route-path" d="${d}"/>`}
function breadcrumbs(){const b=$('#breadcrumbs');b.innerHTML=state.focus==='system'?'<button>UEE</button><span>/</span><button class="is-current">Stanton</button>':`<button>UEE</button><span>/</span><button data-system>Stanton</button><span>/</span><button class="is-current">${esc(state.focus)}</button>`;$('[data-system]',b)?.addEventListener('click',()=>focus('system'))}
function focus(name){state.focus=name;state.selected=null;state.transform={x:0,y:0,scale:1};renderMap();context(name==='system'?null:maps[name][0]);$('#focusSelected').disabled=true}
function context(n){$('#contextType').textContent=n?n.type:'System overview';$('#contextTitle').textContent=n?n.name:'Stanton';$('#contextDescription').textContent=n?n.description:'Four major planetary jurisdictions and their orbital infrastructure.'}
function tip(e,n){el.tooltip.innerHTML=`<strong>${esc(n.name)}</strong><span>${esc(n.type)} · ${esc(n.description)}</span>`;el.tooltip.classList.add('is-visible');moveTip(e)}
function moveTip(e){const r=el.stage.getBoundingClientRect();el.tooltip.style.left=`${Math.min(e.clientX-r.left+14,r.width-245)}px`;el.tooltip.style.top=`${Math.min(e.clientY-r.top+14,r.height-85)}px`}
function applyTransform(){const t=state.transform;el.viewport.style.transform=`translate(${t.x}px,${t.y}px) scale(${t.scale})`}
function mapControls(){let pan=false,start;el.stage.onpointerdown=e=>{if(e.target.closest('.map-toolbar,.map-node'))return;pan=true;start={x:e.clientX-state.transform.x,y:e.clientY-state.transform.y};el.stage.classList.add('is-panning');el.stage.setPointerCapture(e.pointerId)};el.stage.onpointermove=e=>{if(!pan)return;state.transform.x=e.clientX-start.x;state.transform.y=e.clientY-start.y;applyTransform()};el.stage.onpointerup=()=>{pan=false;el.stage.classList.remove('is-panning')};el.stage.addEventListener('wheel',e=>{e.preventDefault();state.transform.scale=Math.max(.65,Math.min(2.4,state.transform.scale*(e.deltaY>0?.9:1.1)));applyTransform()},{passive:false});$('#zoomIn').onclick=()=>{state.transform.scale=Math.min(2.4,state.transform.scale*1.18);applyTransform()};$('#zoomOut').onclick=()=>{state.transform.scale=Math.max(.65,state.transform.scale/1.18);applyTransform()};$('#fitMap').onclick=()=>{state.transform={x:0,y:0,scale:1};applyTransform()};$('#focusSelected').onclick=()=>state.selected?.focus&&focus(state.selected.focus)}
function reset(){localStorage.removeItem('sc-companion-planner-v1');Object.assign(state,{...defaults,contracts:defaults.contracts.map(x=>({...x})),calculated:false,active:false,route:[],focus:'system',selected:null});el.family.value=state.family;variants();el.start.value=state.start;renderContracts();updateShip();dirty();toast('Planner reset to the sample run.')}
function init(){load();initShips();el.start.value=state.start;renderContracts();updateShip();autocomplete();mapControls();renderMap();context(null);$('#addContract').onclick=()=>{state.contracts.push({commodity:'',scu:1,pickup:'',delivery:'',reward:0,note:''});renderContracts();dirty();requestAnimationFrame(()=>el.contracts.lastElementChild?.scrollIntoView({behavior:'smooth',block:'nearest'}))};el.start.oninput=()=>{state.start=el.start.value;metrics();dirty(false)};el.start.onchange=()=>{save();renderMap()};el.calc.onclick=calculate;el.startRoute.onclick=startRoute;$('#resetPlanner').onclick=reset;$('#saveButton').onclick=()=>{save();toast('Planner saved in this browser.')};$('#expandTimeline').onclick=()=>toast('Timeline is already showing all planned stops.');$$('.nav-item').forEach(b=>b.onclick=()=>{if(b.dataset.view!=='planner')toast(`${b.textContent} is reserved for the next pass.`)});$$('[data-map-mode]').forEach(b=>b.onclick=()=>{$$('[data-map-mode]').forEach(x=>x.classList.remove('is-active'));b.classList.add('is-active');el.overlay.style.opacity=b.dataset.mapMode==='route'?'1':'.48'})}
document.addEventListener('DOMContentLoaded',init);
