'use strict';

(function exposeRoadmap(root) {
  const releases = Object.freeze([
    Object.freeze({ version: '0.1', status: 'done', title: 'Foundation', summary: 'Clean modular application base.', changes: Object.freeze(['Application shell', 'Local state', 'Mission and location models']) }),
    Object.freeze({ version: '0.2', status: 'done', title: 'Mission intake', summary: 'Turn compact text into structured contracts.', changes: Object.freeze(['Mission text parser', 'Cargo lots', 'Mission provenance']) }),
    Object.freeze({ version: '0.3', status: 'done', title: 'Cargo planning', summary: 'Initial cargo zones and placement logic.', changes: Object.freeze(['Logical zones', 'Vertical layers', 'Delivery-access priority']) }),
    Object.freeze({ version: '0.4', status: 'done', title: 'Guided route', summary: 'One operational stop at a time.', changes: Object.freeze(['Current destination', 'Complete and previous', 'Pickup before delivery']) }),
    Object.freeze({ version: '0.5', status: 'done', title: 'Live operations', summary: 'Cargo state follows route progress.', changes: Object.freeze(['Load and unload queue', 'Onboard manifest', 'Stable planned slots']) }),
    Object.freeze({ version: '0.6', status: 'done', title: 'Manual corrections', summary: 'Reality can override the generated plan.', changes: Object.freeze(['Actual SCU', 'Cargo status override', 'Lost cargo tracking']) }),
    Object.freeze({ version: '0.7', status: 'done', title: 'Route corrections', summary: 'Safely change future stops.', changes: Object.freeze(['Skip and reopen', 'Dependency-safe reorder', 'In-app changelog']) }),
    Object.freeze({ version: '0.8', status: 'done', title: 'Route planner', summary: 'Compare transparent valid route estimates.', changes: Object.freeze(['Fastest profile', 'Per-leg estimates', 'Hangar quantum factor']) }),
    Object.freeze({ version: '0.9', status: 'done', title: 'Cargo-aware routing', summary: 'Capacity and cargo exposure affect route choice.', changes: Object.freeze(['Minimum onboard profile', 'Protect cargo margin', 'Off-grid allowance', 'Cargo-first hierarchy']) }),
    Object.freeze({ version: '0.10', status: 'done', title: 'Consolidated workspaces', summary: 'Fewer pages and configurable cargo zones.', changes: Object.freeze(['Six primary workspaces', 'Expandable operational drawer', 'Contextual Location Intel', 'Linear roadmap', 'Per-ship Cargo Zone Editor']) }),
    Object.freeze({ version: '0.11', status: 'done', title: 'Interface rebuild', summary: 'First shared visual hierarchy and responsive shell.', changes: Object.freeze(['Shared spacing and typography', 'Collapsible navigation', 'Mobile bottom navigation', 'Consistent primary actions']) }),
    Object.freeze({ version: '0.12', status: 'done', title: 'Drake MFD pass', summary: 'Initial industrial identity and docked operational tools.', changes: Object.freeze(['Docked desktop utility MFD', 'No duplicated operation hero', 'SVG mark and icon family', 'Industrial amber panel chrome']) }),
    Object.freeze({ version: '0.13', status: 'done', title: 'MFD layout rebuild', summary: 'Replace web-dashboard proportions with compact cockpit displays.', changes: Object.freeze(['Compact application chrome', 'Amber primary operation screen', 'Route index display', 'Function keys', 'Reliable panel close controls']) }),
    Object.freeze({ version: '0.14', status: 'current', title: 'Design system foundation', summary: 'Stop page-by-page invention and establish a reusable multi-MFD UI system.', changes: Object.freeze(['Primitive and semantic design tokens', 'Canonical buttons, panels, fields and statuses', 'Canonical icon metadata', 'Visible Development UI Kit', 'Manufacturer theme contract', 'Documented research and implementation rules']) }),
    Object.freeze({ version: '0.15', status: 'next', title: 'Operations components', summary: 'Rebuild live hauling around panel-native components only.', changes: Object.freeze(['Clear pickup and drop-off instructions', 'Panel-native Moves, Cargo, Adjust and Route views', 'No embedded full-page layouts', 'Reviewed desktop and mobile screenshots']) }),
    Object.freeze({ version: '0.16', status: 'future', title: 'Fleet visual rebuild', summary: 'Turn ship configuration into a visual operational workspace.', changes: Object.freeze(['Ship silhouette or wireframe', 'Cargo-zone schematic', 'Readable ship selector', 'Design-system fields and actions']) }),
    Object.freeze({ version: '0.17', status: 'future', title: 'Route-first Starmap', summary: 'Prioritize the active route over free-camera spectacle.', changes: Object.freeze(['Predictable pan and zoom', 'Fit active route', 'Readable route nodes', 'Location focus and reset controls']) }),
    Object.freeze({ version: '0.18', status: 'future', title: 'Missions and Planner migration', summary: 'Move intake and route decisions onto the approved component set.', changes: Object.freeze(['Structured mission editor', 'Compact parsed-contract review', 'Planner decision hierarchy', 'Shared form and status components']) }),
    Object.freeze({ version: '0.19', status: 'future', title: 'UI hardening', summary: 'Review the rebuilt interface as one product.', changes: Object.freeze(['Screenshot regression set', 'Keyboard and close behaviour', 'Responsive review', 'Density and second-monitor checks']) }),
    Object.freeze({ version: '0.20', status: 'future', title: 'Mission validation', summary: 'Catch unclear or incomplete mission input before generation.', changes: Object.freeze(['Field confidence', 'Actionable warnings', 'Inline correction review']) }),
    Object.freeze({ version: '0.21', status: 'future', title: 'Location danger context', summary: 'Show sourced operational danger without inventing a risk score.', changes: Object.freeze(['Source confidence', 'Cargo exposure warnings', 'Richer service profiles']) }),
    Object.freeze({ version: '0.22', status: 'future', title: 'Fleet loadouts', summary: 'Make ship configuration affect more estimates.', changes: Object.freeze(['Structured components', 'Saved loadouts', 'Performance inputs']) }),
    Object.freeze({ version: '0.23', status: 'future', title: 'Session history', summary: 'Keep completed runs and operational outcomes.', changes: Object.freeze(['Completed sessions', 'Timings and incidents', 'Reusable session templates']) }),
    Object.freeze({ version: '0.24', status: 'future', title: 'Companion pairing', summary: 'Operate the active route from a second device.', changes: Object.freeze(['Short-code pairing', 'Complete-next control', 'Focused mobile view']) }),
    Object.freeze({ version: '0.25', status: 'future', title: 'Expanded universe data', summary: 'Broader location and map coverage with visible provenance.', changes: Object.freeze(['More destinations', 'Data review metadata', 'Verified geometry where available']) }),
    Object.freeze({ version: '0.26', status: 'future', title: 'Trading foundation', summary: 'Use spare capacity without hiding market uncertainty.', changes: Object.freeze(['Route-compatible trades', 'Timestamped sources', 'Budget and capacity limits']) }),
    Object.freeze({ version: '0.27', status: 'future', title: 'Assisted intake', summary: 'Optional automation after the manual workflow is reliable.', changes: Object.freeze(['Import confidence', 'OCR review flow', 'Game.log adapters']) }),
    Object.freeze({ version: '0.28', status: 'future', title: 'Release hardening', summary: 'Polish, portability and regression coverage.', changes: Object.freeze(['Export and backup', 'Accessibility pass', 'Performance and recovery']) }),
    Object.freeze({ version: '1.0', status: 'future', title: 'Complete companion workflow', summary: 'A reliable end-to-end mission, route and cargo session.', changes: Object.freeze(['Stable primary workflow', 'Documented data boundaries', 'Production-ready release']) })
  ]);

  const api = Object.freeze({ releases, currentVersion: '0.14' });
  root.SCCompanionRoadmap = api;
  if (typeof module !== 'undefined' && module.exports) module.exports = api;
}(typeof globalThis !== 'undefined' ? globalThis : window));
