'use strict';

(function exposeRoadmap(root) {
  const releases = Object.freeze([
    Object.freeze({ version: '0.1', status: 'done', title: 'Foundation', summary: 'Clean modular application base.', changes: Object.freeze(['Application shell', 'Local state', 'Mission and location models']) }),
    Object.freeze({ version: '0.2', status: 'done', title: 'Mission intake', summary: 'Turn compact text into structured contracts.', changes: Object.freeze(['Mission text parser', 'Cargo lots', 'Mission provenance']) }),
    Object.freeze({ version: '0.3', status: 'done', title: 'Cargo planning', summary: 'Initial cargo zones and placement logic.', changes: Object.freeze(['Logical zones', 'Vertical layers', 'Delivery-access priority']) }),
    Object.freeze({ version: '0.4', status: 'done', title: 'Guided route', summary: 'One operational stop at a time.', changes: Object.freeze(['Current destination', 'Complete and previous', 'Pickup before delivery']) }),
    Object.freeze({ version: '0.5', status: 'done', title: 'Live operations', summary: 'Cargo state follows route progress.', changes: Object.freeze(['Load and unload queue', 'Onboard manifest', 'Stable planned slots']) }),
    Object.freeze({ version: '0.6', status: 'done', title: 'Manual corrections', summary: 'Reality can override the generated plan.', changes: Object.freeze(['Actual SCU', 'Cargo status override', 'Lost cargo tracking']) }),
    Object.freeze({ version: '0.7', status: 'done', title: 'Route corrections', summary: 'Safely change future stops.', changes: Object.freeze(['Skip and reopen', 'Dependency-safe reorder', 'In-app changelog']) }),
    Object.freeze({ version: '0.8', status: 'done', title: 'Route planner', summary: 'Compare transparent valid route estimates.', changes: Object.freeze(['Fastest profile', 'Per-leg estimates', 'Hangar quantum factor']) }),
    Object.freeze({ version: '0.9', status: 'done', title: 'Cargo-aware routing', summary: 'Capacity and cargo exposure affect route choice.', changes: Object.freeze(['Minimum onboard profile', 'Protect cargo margin', 'Off-grid allowance', 'Cargo-first hierarchy']) }),
    Object.freeze({ version: '0.10', status: 'done', title: 'Consolidated workspaces', summary: 'Fewer pages and configurable cargo zones.', changes: Object.freeze(['Six primary workspaces', 'Contextual operational tools', 'Linear roadmap', 'Per-ship Cargo Zone Editor']) }),
    Object.freeze({ version: '0.11', status: 'done', title: 'Interface rebuild attempt', summary: 'Initial visual hierarchy and responsive navigation.', changes: Object.freeze(['Unified spacing and controls', 'Desktop and mobile navigation', 'Reduced page count']) }),
    Object.freeze({ version: '0.12', status: 'done', title: 'Drake visual pass', summary: 'Initial industrial identity and auxiliary display.', changes: Object.freeze(['Amber industrial treatment', 'Docked tool display', 'Original icon family']) }),
    Object.freeze({ version: '0.13', status: 'done', title: 'MFD proportion pass', summary: 'Compact cockpit proportions and reliable panel closing.', changes: Object.freeze(['Compact operation display', 'Route index', 'Function keys', 'Reliable close behaviour']) }),
    Object.freeze({ version: '0.14', status: 'done', title: 'Design system foundation', summary: 'A reusable source for tokens, components and manufacturer themes.', changes: Object.freeze(['Semantic design tokens', 'Canonical buttons and icons', 'Development UI Kit', 'Manufacturer theme contract']) }),
    Object.freeze({ version: '0.15', status: 'done', title: 'Clean UI rebuild', summary: 'Replace the accumulated visual stack with one clean interface generation.', changes: Object.freeze(['Single page-layout entry', 'Native Operations tools', 'Fleet schematic and zone editor', 'Route-first Starmap', 'Missions and Planner migration']) }),
    Object.freeze({ version: '0.16', status: 'done', title: 'Interstellar navigation', summary: 'Make Stanton, Pyro and Nyx mission routes operational with transparent estimates.', changes: Object.freeze(['Official Alpha 4.9 web snapshot', 'Checkmate, Orbituary, Ruin and Levski registry', 'Current jump topology', 'Normal-space distance estimates', 'Navigation time ranges in Planner, Operations and Starmap', 'Canonical readable typography']) }),
    Object.freeze({ version: '0.17', status: 'done', title: 'Visual hardening', summary: 'Enforce responsive, keyboard and accessibility behaviour in real browsers.', changes: Object.freeze(['Chromium matrix for no-route, active and completed sessions', '1664, 1366, 430 and 390 pixel viewport coverage', 'All Operations tools open and expanded with focus containment and return', 'Visible keyboard focus and arrow-key tab navigation', '44 px mobile targets and stacked cargo-zone editing', 'Reduced-motion and forced-colour contracts', 'Deterministic clean-shell runtime initialization', 'Long-content and multiple-ship regression coverage']) }),
    Object.freeze({ version: '0.18', status: 'done', title: 'Mission validation', summary: 'Review mission fields and resolve uncertainty before a route can be generated.', changes: Object.freeze(['Per-field confidence for action, location and cargo syntax', 'Blocking errors separated from reviewable warnings', 'Inline mission title, action, location and cargo correction', 'Explicit confirmation for custom locations', 'Original and reviewed source retained separately', 'Line provenance carried into cargo lots and route operations', 'Stale-review protection after source edits', 'Chromium correction and ambiguity workflows']) }),
    Object.freeze({ version: '0.19', status: 'done', title: 'Location context', summary: 'Separate sourced facts, reviewed services, derived cargo guidance and unavailable data.', changes: Object.freeze(['Shared Location Context model for Planner and Operations', 'Official and community source ledger with review dates', 'Freshness states for reviewed location data', 'Categorical cargo-exposure guidance without a universal risk score', 'Missing services shown as unavailable rather than invented', 'String-based cargo risk heuristic removed', 'Route and Planner stop context', 'Responsive source and facility detail interface']) }),
    Object.freeze({ version: '0.20', status: 'done', title: 'Fleet loadouts', summary: 'Make named ship configurations drive operational estimates without changing ship identity.', changes: Object.freeze(['Structured component slots and provenance', 'Automatic migration of legacy free-text ship records', 'Named loadouts saved per ship instance', 'Active-loadout switching', 'Loadout-aware quantum, cargo and handling estimates', 'Visible assumptions and unavailable component data', 'Responsive Fleet editor and browser coverage']) }),
    Object.freeze({ version: '0.21', status: 'done', title: 'UX foundation and Starmap 2.0', summary: 'Rebuild navigation around orientation, selection and real user tasks.', changes: Object.freeze(['Itinerary, System and Network as distinct navigation layers', 'Persistent selected-object state', 'Current, next and final objective orientation', 'Pan, zoom, fit and center-current controls', 'Collapsible route and detail context', 'Dedicated mobile bottom-sheet interaction', 'Keyboard navigation and visible map focus', 'Task-based browser validation and screenshot review']) }),
    Object.freeze({ version: '0.22', status: 'current', title: 'Expanded universe data', summary: 'Resolve normal hauling stations and surface facilities through sourced data with complete operational context.', changes: Object.freeze(['130 normalized location records and 84 operational destinations', '34 stations, spaceports, gateways and interstellar destinations', '43 surface industrial or research outposts and 7 distribution centers', 'Complete fuel, food, medical, cargo, refinery, rental, vehicle and trade profiles', 'Destination-specific static risk separated from cargo exposure', 'Punctuation-tolerant in-game aliases and stable navigation targets', 'Finite Starmap anchors with explicit schematic geometry status', 'Expanded mission, Location Intel and multi-viewport Chromium verification']) }),
    Object.freeze({ version: '0.23', status: 'next', title: 'Game.log assisted intake', summary: 'Use Star Citizen logs as the primary automated mission-intake source while preserving review and provenance.', changes: Object.freeze(['Opt-in Game.log file import', 'Incremental mission and contract event extraction', 'Duplicate and replay protection', 'Source-line and event provenance', 'Confidence review before route replacement', 'Graceful fallback when log events are incomplete']) }),
    Object.freeze({ version: '0.24', status: 'future', title: 'OCR assisted intake', summary: 'Use screenshots as a secondary intake path through the same validation workflow.', changes: Object.freeze(['Screenshot and image import', 'OCR field extraction with confidence', 'Image-to-field provenance', 'Inline correction before generation', 'Reuse of the existing mission validation pipeline']) }),
    Object.freeze({ version: '0.25', status: 'future', title: 'Release hardening', summary: 'Make the core companion safe to update, recover and use across supported browsers.', changes: Object.freeze(['Versioned export, backup and restore', 'Explicit local-data migrations', 'Recovery from partial or corrupt state', 'Performance coverage with large routes and location datasets', 'Cross-browser and offline/static deployment checks', 'Full accessibility and release checklist']) }),
    Object.freeze({ version: '1.0', status: 'future', title: 'Core companion release', summary: 'A reliable mission-to-execution workflow built around sourced locations and reviewable assisted intake.', changes: Object.freeze(['Manual, Game.log and OCR mission intake', 'Validated route and cargo generation', 'Stable Operations workflow', 'Documented data and privacy boundaries', 'Production-ready local-first release']) })
  ]);

  const api = Object.freeze({ releases, currentVersion: '0.22' });
  root.SCCompanionRoadmap = api;
  if (typeof module !== 'undefined' && module.exports) module.exports = api;
}(typeof globalThis !== 'undefined' ? globalThis : window));
