'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

function read(file) {
  return fs.readFileSync(path.join(__dirname, '..', file), 'utf8');
}

test('operations owns cargo, moves and correction tools', () => {
  const shell = read('workspace-shell.js');
  assert.match(shell, /data-workspace-pane="moves"/);
  assert.match(shell, /data-workspace-pane="cargo"/);
  assert.match(shell, /data-workspace-pane="corrections"/);
  assert.match(shell, /data-workspace-pane="route-tools"/);
  assert.match(shell, /internalize\(loadOperations\)/);
  assert.match(shell, /internalize\(cargo\)/);
  assert.match(shell, /corrections\.remove\(\)/);
  assert.match(shell, /routeCorrections\.remove\(\)/);
});

test('location intel and changelog become contextual tools', () => {
  const shell = read('workspace-shell.js');
  assert.match(shell, /locations-context-tool/);
  assert.match(shell, /data-development-tab="changelog"/);
  assert.match(shell, /parentView === 'route'/);
});

test('old blueprint pages are no longer generated by the product shell', () => {
  const shell = read('product-shell.js');
  ['overviewTemplate', 'shipCatalogTemplate', 'tradingTemplate', 'automationTemplate'].forEach((name) => assert.doesNotMatch(shell, new RegExp(name)));
  assert.match(shell, /renderDynamicHosts/);
});

test('live cargo surfaces resolve saved ship zones', () => {
  const cargoView = read('cargo-view.js');
  const operations = read('load-operations-view.js');
  assert.match(cargoView, /zoneModel\.resolveModel/);
  assert.match(operations, /zoneModel\.resolveModel/);
  assert.match(cargoView, /cargoZoneOverrides/);
  assert.match(operations, /cargoZoneOverrides/);
});

test('secondary content is visually subordinate to primary operations', () => {
  const css = read('workspace-consolidation.css');
  assert.match(css, /current-stop-card > h3/);
  assert.match(css, /route-stop-list li:not\(\.is-current\)/);
  assert.match(css, /operations-command-strip/);
  assert.match(css, /workspace-drawer/);
});
